### PR TITLE
Add options for loading initial squared gradients

### LINKED ISSUE #170: Training does not resume where left off
I have been training my own GloVe models for my job, and I noticed that training does not resume properly when loading the output of one run as the initial parameters of another. The cost at the beginning of the second run is higher than at the end of the first run, and after a couple of iterations, it spikes by over an order of magnitude before eventually going back down again.

I determined that the issue is that although we have the option of saving parameters and squared gradients, we can only load the parameters. Modifying the code to also allow the loading of squared gradients results in the second run pick off right where the first one ended.

I will be submitting a PR shortly with this fix to allow proper checkpointing and resuming. Without these changes, there isn't much point to resuming if it can fail so horribly.

### PR DESCRIPTION
**Pull request by aphedges**
I made some code changes to fix #170.

I created two new parameters, `-init-gradsq-file` and `-load-init-gradsq` that correspond to `-init-param-file` and `-load-init-param`. Most of the code between the two sets of parameters is exactly the same.

### CODE REVIEW

**Comment by AngledLuffa** [comment]
Thanks for catching this!  As you point out, the code blocks are almost identical.  Would you mind refactoring this?  If that's not your cup of tea, I should be able to do so myself later.

**Comment by aphedges** [comment]
Thanks for responding so quickly! I think I can refactor it. I'll comment here again when I'm done.

**Comment by aphedges** [comment]
I have refactored the code. I had to make some text more generic to work for both types of files, and I fixed two other typos. Please let me know if you have any more feedback.

**Comment by AngledLuffa** [comment]
Thanks!  I merged this.

**Comment by aphedges** [comment]
Thank you very much!

**Comment by AngledLuffa** [comment]
I also added a test to the `randomization.test.sh` script which verifies that the training continues exactly as it was when it is reloaded like this.

**Comment by aphedges** [comment]
I'm glad to have some additional tests in place for this.

**Pull request merged**
