### PR TITLE
Octave can be used in demo in lieu of matlab.

### PR DESCRIPTION
**Pull request by cho0o0**

### CODE REVIEW

**Comment by Russell91** [comment]
This would be nice to have. Can you confirm that the numerical results are *exactly* the same as in the matlab version though?

**Comment by cho0o0** [comment]
Since I've got no matlab on my pc, I will try to run the python program later to check if the results are same or not.

**Comment by cho0o0** [comment]
Sorry for my late. I used the corpus in demo script and default settings. The results appear to be total same.
octave
(Octave)
python
(Python)

**Comment by Russell91** [comment]
Perfect, thank you for the contribution!

**Pull request merged**
